# loosely pin
FROM verdaccio/verdaccio:5

USER root

COPY plugins /verdaccio/plugins
RUN cd /verdaccio/plugins && sh install.sh
COPY config/config.yaml /verdaccio/conf/config.yaml

# revert the user back
USER verdaccio
