# Use a specific version to avoid unexpected changes
FROM verdaccio/verdaccio:5

USER root

# Copy plugins to the intended directory
COPY plugins /verdaccio/plugins

# Run installation scripts for plugins
RUN cd /verdaccio/plugins && sh install.sh

# Copy Verdaccio's configuration file
COPY config/config.yaml /verdaccio/conf/config.yaml

# Revert to the Verdaccio user for security
USER verdaccio
